apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
# patchesStrategicMerge:
# - enable-sops-patch.yml        
patches:
- patch: |- 
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      decryption:
        provider: sops  
